\\ Exact semilinear branch-exchange covariance at the HJLPPZ p=23
\\ stable Gauss valuation.
\\
\\ The nontrivial automorphism of Q_23(s)/Q_23 sends
\\   s |-> -s, z |-> tau(z)=z/(z-1).
\\ This script proves that the residual norm, logarithmic Swan form,
\\ tame Kummer parameter, and graded Swan coefficient are compatible
\\ with that involution.

z = 'z;
u = 'u;
p = 23;

tau = z/(z-1);
E = Mod(8,p)*z^9 + Mod(7,p)*z^8 + Mod(11,p)*z^7 + Mod(16,p)*z^6 + Mod(3,p)*z^5 + Mod(19,p)*z^4 + Mod(21,p)*z^3 + Mod(21,p)*z^2 + Mod(17,p)*z + Mod(15,p);
Y = -E/(z-1)^5;
R = z^15*(z^2+Mod(13,p)*z+Mod(10,p))^11/(z-2)^37;
B0 = (z-2)^8*(z-1)/E;
swanform = deriv(Y,z)/Y;

\\ The invariant field of tau on F_23(z) is generated by
\\   u=z^2/(z-1).
\\ In that coordinate the residual norm is a quartic polynomial.  Its
\\ critical profile is (4), (3,1), (2,1,1), hence its geometric monodromy
\\ is S4: a transitive degree-four group containing a 4-cycle and a
\\ 3-cycle can only be S4.
quotient_coordinate = z^2/(z-1);
H = Mod(15,p)*(u^4-u^3+Mod(8,p)*u^2+Mod(4,p)*u+1);
shabat_source = Mod(4,p)*(u-4);
shabat_target = Mod(4,p)*(H-Mod(18,p));
wild_phase = Mod(12-4,p)/Mod(10-4,p);
wild_phase_reversal = wild_phase/(wild_phase-1);

tau_is_involution = simplify(subst(tau,z,tau)-z) == 0;
Y_is_invariant = simplify(subst(Y,z,tau)-Y) == 0;
swanform_is_invariant = simplify(subst(swanform,z,tau)*deriv(tau,z)-swanform) == 0;
R_is_anti_invariant = simplify(subst(R,z,tau)+R) == 0;
B0_is_invariant = simplify(subst(B0,z,tau)-B0) == 0;
E_functional_equation = simplify((z-1)^10*subst(E,z,tau)-E) == 0;
quotient_coordinate_is_invariant =
  simplify(subst(quotient_coordinate,z,tau)-quotient_coordinate) == 0;
residual_quartic_identity =
  simplify(subst(H,u,quotient_coordinate)-Y) == 0;
quartic_derivative_identity =
  deriv(H,u) == Mod(14,p)*(u-4)^2*(u-10);
quartic_triple_fibre_identity =
  H-Mod(18,p) == Mod(15,p)*(u-4)^3*(u-12);
quartic_double_fibre_identity =
  H-Mod(1,p) == Mod(15,p)*(u-10)^2*(u^2+Mod(19,p)*u+Mod(12,p));
graded_swan_quotient_identity =
  simplify(subst(-(u-4)^4/H,u,quotient_coordinate)-B0) == 0;
shabat_normal_form_identity =
  shabat_target == shabat_source^3*(4-3*shabat_source);
intrinsic_phase_identity =
  wild_phase == Mod(9,p) && wild_phase_reversal == Mod(4,p);

if(!tau_is_involution, error("the target branch exchange is not involutive"));
if(!Y_is_invariant, error("the residual norm is not branch-exchange invariant"));
if(!swanform_is_invariant, error("the logarithmic Swan differential is not invariant"));
if(!R_is_anti_invariant, error("the Kummer initial unit does not acquire the required sign"));
if(!B0_is_invariant, error("the graded Swan rational coefficient is not invariant"));
if(!E_functional_equation, error("the polynomial functional equation for E failed"));
if(!quotient_coordinate_is_invariant, error("u does not generate a tau-invariant quotient coordinate"));
if(!residual_quartic_identity, error("the residual norm does not factor through H(u)"));
if(!quartic_derivative_identity, error("the quartic critical divisor changed"));
if(!quartic_triple_fibre_identity, error("the quartic triple fibre changed"));
if(!quartic_double_fibre_identity, error("the quartic double fibre changed"));
if(!graded_swan_quotient_identity, error("the Swan coefficient does not descend to the quartic quotient"));
if(!shabat_normal_form_identity, error("the residual quartic Shabat normal form changed"));
if(!intrinsic_phase_identity, error("the residual quartic intrinsic phase changed"));

\\ Under s |-> -s the sign in R(tau(z))=-R(z) cancels, so s*R(z)
\\ is fixed.  Since 11 divides 23-1, mu_11 lies in Q_23 and is fixed by
\\ the quadratic constant involution.  Thus the invariant Kummer equation
\\ X^11=sR(z) admits an involutive lift fixing a chosen Kummer root xi.
if((p-1)%11 != 0, error("mu_11 is not contained in the unramified units"));

squares = [1,2,3,4,6,8,9,12,13,16,18];
nonsquares = [5,7,10,11,14,15,17,19,20,21,22];
negated_squares = vector(#squares,i,(-squares[i])%p);
if(negated_squares != [22,21,20,19,17,15,14,11,10,7,5], error("negation does not carry the square packet to the nonsquare packet"));
if(Set(negated_squares) != Set(nonsquares), error("the square and nonsquare packets are not exchanged by reversal"));

print("object\tinvariant\tvalue\tstatus");
print("target\tbranch_exchange\t(s,z)->(-s,z/(z-1))\torder_2");
print("residual_norm\tfunctional_equation\tY(tau(z))=Y(z)\texact_over_F23(z)");
print("residual_polynomial\tsemilinear_symmetry\tV^23=Y(z)\tV_fixed_on_residue");
print("swan_differential\tfunctional_equation\ttau^*dlog(Y)=dlog(Y)\texact_over_F23(z)");
print("tame_kummer_unit\tfunctional_equation\tR(tau(z))=-R(z)\tsR(z)_fixed_under_s_to_-s");
print("tame_kummer_root\tinvolutive_lift\txi^11=sR(z),_iota(xi)=xi\tmu11_subset_Q23_and_11_odd");
print("graded_swan_coefficient\tfunctional_equation\tB0(tau(z))=B0(z)\tin(b_H)=8s^2xiB0_fixed");
print("involution_quotient\tinvariant_coordinate\tu=z^2/(z-1)\tF23(z)^tau=F23(u)");
print("residual_norm_quotient\tquartic_factorization\tY=15*(u^4-u^3+8u^2+4u+1)\texact_over_F23(u)");
print("residual_quartic\tcritical_passport\tinfinity:(4),18:(3,1),1:(2,1,1)\tgeometric_monodromy_S4");
print("residual_quartic\tunique_triple_critical_point\tu=4\tH(u)-18=15*(u-4)^3*(u-12)");
print("residual_quartic\tshabat_normal_form\tX=4*(u-4),W=4*(H-18),W=X^3*(4-3X)\tcritical_coordinate_value_is_not_intrinsic");
print("residual_quartic\tintrinsic_cross_ratio_phase\t(u_simple-u_triple)/(u_double-u_triple)=9\torientation_reversal_9_maps_to_4");
print("graded_swan_quotient\tquartic_formula\tB0=-(u-4)^4/H(u)\texact_over_F23(u)");
print("wild_character_packets\tbranch_exchange\tsquares<->nonsquares\t23A<->23B");
print("# PASS_P23_SEMILINEAR_COVARIANCE_CERTIFICATE");
quit(0);
