#!/usr/bin/env python3
"""Emit the self-contained Magma certificates used by the public suite."""

from __future__ import annotations

import argparse
import difflib
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "verification" / "magma"
HJLPPZ = ROOT / "families" / "hjlppz-2026" / "polynomial_F.gp"
ELKIES = ROOT / "families" / "elkies-2013" / "elkies_cover.gp"

HEADER = r'''// Generated by scripts/emit_magma_suite.py.  Do not edit by hand.
// Apache-2.0.  See ../../LICENSE and ../../NOTICE.
// Self-contained for the 50,000-byte, 60-second Sydney Magma Calculator.

procedure Must(flag, message)
    if not flag then
        print "CERTIFICATE_FAILURE: " cat message;
        quit;
    end if;
end procedure;

function V23Integer(n)
    if n eq 0 then
        return 10^9;
    end if;
    n := Abs(Integers()!n);
    value := 0;
    while n mod 23 eq 0 do
        n div:= 23;
        value +:= 1;
    end while;
    return value;
end function;

function V23Rational(q)
    if q eq 0 then
        return 10^9;
    end if;
    return V23Integer(Numerator(q)) - V23Integer(Denominator(q));
end function;

'''


def hjlppz_preamble() -> str:
    source = HJLPPZ.read_text()
    terms = []
    pattern = re.compile(r"b\[(\d+)\]\s*\+=\s*\(([-\d]+)\)\*T\^(\d+);")
    for index, coefficient, exponent in pattern.findall(source):
        terms.append(f"b[{index}] +:= ({coefficient})*T^{exponent};")
    if len(terms) != 119:
        raise RuntimeError(f"expected 119 HJLPPZ terms, found {len(terms)}")
    return r'''Q := Rationals();
QT<T> := PolynomialRing(Q);
b := [ QT!0 : index in [1..23] ];
''' + "\n".join(terms) + r'''

KQT := FieldOfFractions(QT);
RV<V> := PolynomialRing(KQT);
F := V^23 + &+[ (KQT!b[index])/(T^2+23)^(Floor(5*index/23))*V^(23-index)
                  : index in [2..23] ];
Must(Degree(F) eq 23, "the HJLPPZ polynomial lost degree 23");

'''


def elkies_preamble() -> str:
    source = ELKIES.read_text()
    names = ["P2_elkies", "P3_elkies", "P4_elkies", "tau_elkies"]
    assignments = []
    for name in names:
        match = re.search(rf"(?ms)^{name}\s*=\s*(.*?);", source)
        if not match:
            raise RuntimeError(f"could not find {name}")
        expression = " ".join(match.group(1).split())
        assignments.append(f"{name} := {expression};")
    return r'''Qpi<Xpi> := PolynomialRing(Q);
Kpi<pi> := NumberField(Xpi^4-23*Xpi^3+207*Xpi^2-874*Xpi+1472);
g := pi-6;
Must(g^4+g^3+9*g^2-10*g+8 eq 0, "the Elkies quartic changed");
Kx<x> := PolynomialRing(Kpi);
''' + "\n".join(assignments) + r'''
P_elkies := P2_elkies^2*P3_elkies*P4_elkies^4;

function VPi(a)
    if a eq 0 then
        return 10^9;
    end if;
    coefficients := Eltseq(Kpi!a);
    return Min([ 4*V23Rational(coefficients[index])+(index-1)
                 : index in [1..#coefficients] ]);
end function;

F23 := GF(23);
function ResiduePi(a)
    coefficients := Eltseq(Kpi!a);
    Must(Min([ 4*V23Rational(coefficients[index])+(index-1)
               : index in [1..#coefficients] ]) ge 0,
         "attempted to reduce a nonintegral pi-adic element");
    return F23!coefficients[1];
end function;

'''


VERTICAL_BODY = r'''// Exact first vertical-different certificate at characteristic 23.

Qs<Ss> := PolynomialRing(Q);
Ks<ss> := NumberField(Ss^2+23);
Ksz<z> := RationalFunctionField(Ks);
F23z<z23> := RationalFunctionField(F23);
F23zV<V23> := PolynomialRing(F23z);

function VS(a)
    if a eq 0 then
        return 10^9;
    end if;
    coefficients := Eltseq(Ks!a);
    return Min(2*V23Rational(coefficients[1]),
               2*V23Rational(coefficients[2])+1);
end function;

function ResidueS(a)
    coefficients := Eltseq(Ks!a);
    Must(VS(a) ge 0, "attempted to reduce a nonintegral s-adic element");
    return F23!coefficients[1];
end function;

normalized_hj := V23^22;
hj_valuations := [];
for index in [2..22] do
    denominator_order := Floor(5*index/23);
    raw := Evaluate(b[index], ss*z/(2-z))*(2-z)^(2*denominator_order);
    raw_numerator := Numerator(raw);
    raw_denominator := Denominator(raw);
    Must(Degree(raw_denominator) eq 0,
         "HJ substituted numerator did not become a polynomial");
    polynomial := raw_numerator/Coefficient(raw_denominator, 0);
    valuation := Min([ VS(Coefficient(polynomial, degree))
                       : degree in [0..Degree(polynomial)] ])
                 - 2*denominator_order;
    Append(~hj_valuations, valuation);
    Must(valuation ge 2, "HJ derivative coefficient lies below v(23)");
    if valuation eq 2 then
        scale := 23*(-92)^denominator_order;
        reduced := F23z!0;
        for degree in [0..Degree(polynomial)] do
            reduced +:= ResidueS(Coefficient(polynomial, degree)/scale)*z23^degree;
        end for;
        normalized_hj +:= (F23!(23-index))*reduced/(z23-1)^denominator_order
                          *V23^(22-index);
    end if;
end for;
Must(hj_valuations eq [4] cat [2 : index in [1..20]],
     "wrong HJ stable derivative coefficient valuations");
Must(Degree(normalized_hj) eq 22 and normalized_hj ne 0,
     "HJ normalized vertical derivative vanished");
denominator_lcm := LCM([ Denominator(Coefficient(normalized_hj, degree))
                         : degree in [0..22] ]);
denominator_lcm /:= LeadingCoefficient(denominator_lcm);
Must(denominator_lcm eq (z23-1)^3,
     "wrong HJ normalized derivative denominator");
normalized_hj_monic := normalized_hj/LeadingCoefficient(normalized_hj);
Must(IsIrreducible(normalized_hj_monic),
     "HJ normalized derivative is reducible over F23(z)");

endpoint := 8*z23^9+7*z23^8+11*z23^7+16*z23^6+3*z23^5+
            19*z23^4+21*z23^3+21*z23^2+17*z23+15;
residual_constant := endpoint/(z23-1)^5;
residual_hj := V23^23+residual_constant;
Must(Derivative(residual_constant) ne 0,
     "HJ residual polynomial is not purely inseparable irreducible");
different_norm_hj := Resultant(residual_hj, normalized_hj);
tail_quadratic := z23^2+13*z23+10;
expected_norm_hj := z23^30*(z23-2)^102*tail_quadratic^22/(z23-1)^88;
Must(different_norm_hj eq expected_norm_hj,
     "wrong HJ first vertical-different norm");
F23Z<Z23> := PolynomialRing(F23);
Must(IsIrreducible(Z23^2+13*Z23+10),
     "HJ quadratic vertical-different locus unexpectedly split");
residual_norm_hj := -residual_constant;
Must(Derivative(residual_norm_hj)/residual_norm_hj ne 0,
     "HJ residual norm differential vanished");

Kpy<y> := PolynomialRing(Kpi);
scaled_elkies := Evaluate(P_elkies, pi^-1*y)/tau_elkies;
normalized_elkies := Derivative(scaled_elkies)/pi^4;
elkies_valuations := [ VPi(Coefficient(normalized_elkies, degree))
                       : degree in [0..22] ];
Must(elkies_valuations eq
     [7,7,6,6,5,5,4,4,3,3,2,2,1,1,0,0,0,0,0,0,0,0,0],
     "wrong Elkies normalized derivative valuations");
F23Y<Y23> := PolynomialRing(F23);
reduced_elkies := &+[ ResiduePi(Coefficient(normalized_elkies, degree))*Y23^degree
                       : degree in [0..22] ];
expected_elkies := -Y23^14*(Y23-9)^8;
Must(reduced_elkies eq expected_elkies,
     "wrong Elkies first vertical derivative");
F23t<t23> := RationalFunctionField(F23);
F23tY<Yt> := PolynomialRing(F23t);
reduced_elkies_t := &+[ F23t!Coefficient(reduced_elkies, degree)*Yt^degree
                         : degree in [0..22] ];
residual_elkies := 18*Yt^23-t23;
different_norm_elkies := Resultant(residual_elkies, reduced_elkies_t);
Must(different_norm_elkies eq -t23^14*(t23-1)^8,
     "wrong Elkies first vertical-different norm");
residual_norm_elkies := t23/18;
Must(Derivative(residual_norm_elkies)/residual_norm_elkies eq 1/t23,
     "wrong Elkies residual norm differential");

print "cover\tprime\tinvariant\tvalue\tstatus";
print "hjlppz\t23\tderivative_coefficient_valuations\t4,2x20\tminimum_2";
print "hjlppz\t23\tnormalized_vertical_derivative\t22\tirreducible_over_F23(z)";
print "hjlppz\t23\tdifferent_norm_divisor\t0:30,2:102,Q2:22,1:-88,infinity:-88\tQ2=z^2+13z+10_irreducible";
print "hjlppz\t23\tmonogenic_different_exponent\t2\tnormalized_derivative_nonzero";
print "hjlppz\t23\tdiscriminant_exponent\t46\t23_times_different";
print "hjlppz\t23\twild_upper_break\t23/22\tmaximal_fierce_C23_break";
print "hjlppz\t23\tresidual_norm_differential\tdlog(-E(z)/(z-1)^5)\tCartier_fixed";
print "hjlppz\t23\trefined_swan_normalization\tb_H^(-1)_tensor_residual_norm_differential\tb_H=N(sigma(x)/x-1)_required";
print "elkies\t23\tderivative_coefficient_valuations\t7,7,6,6,5,5,4,4,3,3,2,2,1,1,0x9\tminimum_0_after_pi4";
print "elkies\t23\tnormalized_vertical_derivative\t-y^14*(y-9)^8\ttail_centers_0,9";
print "elkies\t23\tdifferent_norm_divisor\t0:14,1:8,infinity:-22\trecovers_4A,2A_contributions";
print "elkies\t23\tmonogenic_different_exponent\t4\tnormalized_derivative_nonzero";
print "elkies\t23\tdiscriminant_exponent\t92\t23_times_different";
print "elkies\t23\twild_upper_break\t23/22\tmaximal_fierce_C23_break";
print "elkies\t23\tresidual_norm_differential\tdt/t\tCartier_fixed";
print "elkies\t23\trefined_swan_normalization\tb_E^(-1)_tensor_residual_norm_differential\tb_E=N(sigma(x)/x-1)_required";
print "# PASS_CHARACTERISTIC_23_VERTICAL_DIFFERENT_MAGMA_CERTIFICATE";
'''


TAME_BODY = r'''// Exact tame degree-11 Kummer-resolvent certificate at characteristic 23.

squares := { (index^2) mod 23 : index in [1..22] };
Must(squares eq {1,2,3,4,6,8,9,12,13,16,18},
     "the quadratic-residue packet changed");
Must((&*[ index : index in squares ]) mod 23 eq 1,
     "the quadratic-residue packet has the wrong product");

q := T^2+23;
discriminant_hj := Discriminant(F);
numerator_factors := Factorization(Numerator(discriminant_hj));
degree_84_factors := [ factor[1] : factor in numerator_factors |
                       Degree(factor[1]) eq 84 and factor[2] eq 2 ];
Must(#degree_84_factors eq 1, "missing HJ degree-84 square factor");
G84_monic := degree_84_factors[1];
denominator_lcm := LCM([ Denominator(Coefficient(G84_monic, degree))
                         : degree in [0..84] ]);
G84_integer := denominator_lcm*G84_monic;
coefficient_gcd := GCD([ Abs(Numerator(Coefficient(G84_integer, degree)))
                         : degree in [0..84] ]);
G84 := G84_integer/coefficient_gcd;
if LeadingCoefficient(G84) lt 0 then
    G84 := -G84;
end if;
a0 := 2^105*3^36*23^37;
AH := a0*T^4*G84/q^44;
Must(AH^2 eq discriminant_hj,
     "wrong HJ oriented discriminant square root");
hH := 2^9*3^3*23^5/q^4;
lambdaH := 2^6*3^3*T^4*G84/23^18;
Must(AH eq hH^11*lambdaH,
     "wrong HJ eleventh-power normalization");

F23W<w> := PolynomialRing(F23);
weighted_minimum := 10^9;
lambda_residue := F23W!0;
for degree in [0..84] do
    coefficient := Coefficient(G84, degree);
    if coefficient ne 0 then
        weight := 2*V23Rational(coefficient)+degree;
        weighted_minimum := Min(weighted_minimum, weight);
        if weight eq 33 then
            Must(degree mod 2 eq 1, "HJ first-grade parity failure");
            first_grade := 2^6*3^3*coefficient/((-23)^((33-degree) div 2));
            lambda_residue +:= (F23!first_grade)*w^(degree+4);
        end if;
    end if;
end for;
Must(weighted_minimum eq 33,
     "wrong HJ weighted valuation of the degree-84 factor");
// The minus sign is the w-coordinate unit; replacing 2-w by w-2 in the
// published z-coordinate cancels it because the denominator exponent is 37.
Must(lambda_residue eq -w^15*(w^2+6)^11,
     "wrong HJ initial tame Kummer parameter");
YH := -b[23]/q^5;
Must(KQT!YH eq -Coefficient(F, 0), "wrong HJ root norm");

Kpit<t> := RationalFunctionField(Kpi);
KpitY<yt> := PolynomialRing(Kpit);
p23 := LeadingCoefficient(P_elkies);
q23 := p23*pi^-23;
raw_elkies := Evaluate(P_elkies, pi^-1*yt)/tau_elkies-t;
leading_elkies := Coefficient(raw_elkies, 23);
Must(leading_elkies eq q23/tau_elkies,
     "wrong Elkies scaled leading coefficient");
monic_elkies := raw_elkies/leading_elkies;
discriminant_elkies := Discriminant(monic_elkies);
sE := (2*g^3+4*g^2+16*g-7)/3;
Must(sE^2 eq -23, "wrong Elkies square root of -23");
Must(VPi(sE) eq 2, "wrong valuation of the Elkies quadratic uniformizer");
hE := 23*tau_elkies*pi^23/p23;
lambdaE := sE*t^7*(t-1)^4;
AE := hE^11*lambdaE;
Must(discriminant_elkies eq AE^2,
     "wrong Elkies oriented discriminant square root");
Must(VPi(hE) eq 4, "wrong Elkies eleventh-power scaling valuation");
Must(ResiduePi(sE/pi^2) eq F23!-3,
     "wrong Elkies initial tame Kummer unit");
Must(ResiduePi(hE/pi^4) eq F23!11,
     "wrong Elkies b-scaling unit");
P0 := Evaluate(P_elkies, 0);
YE := (tau_elkies*t-P0)/q23;
Must(YE eq -Coefficient(monic_elkies, 0), "wrong Elkies root norm");
ye_denominator := Denominator(YE);
Must(Degree(ye_denominator) eq 0, "Elkies root norm denominator changed");
ye_scale := Coefficient(ye_denominator, 0);
Must(ResiduePi(Coefficient(Numerator(YE), 1)/ye_scale) eq F23!9 and
     ResiduePi(Coefficient(Numerator(YE), 0)/ye_scale) eq F23!0,
     "wrong Elkies residual root norm");

print "cover\tprime\tinvariant\tvalue\tstatus";
print "both\t23\toriented_cycle_norm_identity\tA^2=Disc(f)\tA=product_(q_square)C_q";
print "both\t23\tdegree_11_oriented_resolvent\tproduct_(q_square)(U-C_q)\tconstant_term=-A";
print "hjlppz\t23\tdiscriminant_square_root\t2^105*3^36*23^37*T^4*G84(T)/(T^2+23)^44\texact_G84_degree_84";
print "hjlppz\t23\ttame_kummer_parameter\tLambda_H=2^6*3^3*T^4*G84(T)/23^18\tv_s(Lambda_H)=1";
print "hjlppz\t23\ttame_degree_11_resolvent\tX^11-Lambda_H\tEisenstein_over_Q23(s)(z)";
print "hjlppz\t23\ttame_parameter_initial_unit\tz^15*(z^2+13*z+10)^11/(z-2)^37\tLambda_H/s_mod_s";
print "hjlppz\t23\troot_norm_Y_H\t-b_23(T)/(T^2+23)^5\treduces_to_-E(z)/(z-1)^5";
print "hjlppz\t23\tgraded_b_H\tin(b_H)=in(h_H*theta_H/Y_H)\ttheta_H^11=Lambda_H";
print "hjlppz\t23\tgraded_b_H_explicit\t8*s^2*xi_H*(z-2)^8*(z-1)/E(z)\txi_H^11=s*z^15*(z^2+13*z+10)^11/(z-2)^37";
print "elkies\t23\tsqrt_minus_23\t(2*g^3+4*g^2+16*g-7)/3\ts_E^2=-23";
print "elkies\t23\tdiscriminant_square_root\ts_E*(23*tau*pi^23/p_23)^11*t^7*(t-1)^4\texact_over_F(t)";
print "elkies\t23\ttame_kummer_parameter\tLambda_E=s_E*t^7*(t-1)^4\tv_pi(Lambda_E)=2";
print "elkies\t23\ttame_degree_11_resolvent\tX^11-Lambda_E\ttotally_tame_degree_11";
print "elkies\t23\ttame_parameter_initial_unit\t-3*t^7*(t-1)^4\tLambda_E/pi^2_mod_pi";
print "elkies\t23\troot_norm_Y_E\t(tau*t-P(0))/(p_23*pi^-23)\treduces_to_t/18";
print "elkies\t23\tgraded_b_E\tin(b_E)=in(h_E*theta_E/Y_E)\ttheta_E^11=Lambda_E";
print "elkies\t23\tgraded_b_E_explicit\t14*pi^4*xi_E/t\txi_E^11=-3*pi^2*t^7*(t-1)^4";
print "# PASS_CHARACTERISTIC_23_TAME_RESOLVENT_MAGMA_CERTIFICATE";
'''


SEMILINEAR = HEADER + r'''// Exact semilinear branch-exchange covariance at the HJLPPZ p=23 stable Gauss valuation.

F23 := GF(23);
F23z<z> := RationalFunctionField(F23);
F23u<u> := RationalFunctionField(F23);

function SubstituteRational(function_value, argument)
    return Evaluate(Numerator(function_value), argument)/
           Evaluate(Denominator(function_value), argument);
end function;

tau := z/(z-1);
E := 8*z^9+7*z^8+11*z^7+16*z^6+3*z^5+19*z^4+21*z^3+21*z^2+17*z+15;
Y := -E/(z-1)^5;
R := z^15*(z^2+13*z+10)^11/(z-2)^37;
B0 := (z-2)^8*(z-1)/E;
swanform := Derivative(Y)/Y;
quotient_coordinate := z^2/(z-1);
H := 15*(u^4-u^3+8*u^2+4*u+1);
shabat_source := 4*(u-4);
shabat_target := 4*(H-18);
wild_phase := F23!(12-4)/F23!(10-4);
wild_phase_reversal := wild_phase/(wild_phase-1);

Must(SubstituteRational(tau, tau) eq z, "the target branch exchange is not involutive");
Must(SubstituteRational(Y, tau) eq Y, "the residual norm is not branch-exchange invariant");
Must(SubstituteRational(swanform, tau)*Derivative(tau) eq swanform,
     "the logarithmic Swan differential is not invariant");
Must(SubstituteRational(R, tau) eq -R,
     "the Kummer initial unit does not acquire the required sign");
Must(SubstituteRational(B0, tau) eq B0,
     "the graded Swan rational coefficient is not invariant");
Must((z-1)^10*SubstituteRational(E, tau) eq E,
     "the polynomial functional equation for E failed");
Must(SubstituteRational(quotient_coordinate, tau) eq quotient_coordinate,
     "u does not generate a tau-invariant quotient coordinate");
Must(SubstituteRational(H, quotient_coordinate) eq Y,
     "the residual norm does not factor through H(u)");
Must(Derivative(H) eq 14*(u-4)^2*(u-10), "the quartic critical divisor changed");
Must(H-18 eq 15*(u-4)^3*(u-12), "the quartic triple fibre changed");
Must(H-1 eq 15*(u-10)^2*(u^2+19*u+12), "the quartic double fibre changed");
Must(SubstituteRational(-(u-4)^4/H, quotient_coordinate) eq B0,
     "the Swan coefficient does not descend to the quartic quotient");
Must(shabat_target eq shabat_source^3*(4-3*shabat_source),
     "the residual quartic Shabat normal form changed");
Must(wild_phase eq 9 and wild_phase_reversal eq 4,
     "the residual quartic intrinsic phase changed");
Must((23-1) mod 11 eq 0, "mu_11 is not contained in the unramified units");
squares := {1,2,3,4,6,8,9,12,13,16,18};
nonsquares := {5,7,10,11,14,15,17,19,20,21,22};
Must({ (-value) mod 23 : value in squares } eq nonsquares,
     "the square and nonsquare packets are not exchanged by reversal");

print "object\tinvariant\tvalue\tstatus";
print "target\tbranch_exchange\t(s,z)->(-s,z/(z-1))\torder_2";
print "residual_norm\tfunctional_equation\tY(tau(z))=Y(z)\texact_over_F23(z)";
print "residual_polynomial\tsemilinear_symmetry\tV^23=Y(z)\tV_fixed_on_residue";
print "swan_differential\tfunctional_equation\ttau^*dlog(Y)=dlog(Y)\texact_over_F23(z)";
print "tame_kummer_unit\tfunctional_equation\tR(tau(z))=-R(z)\tsR(z)_fixed_under_s_to_-s";
print "tame_kummer_root\tinvolutive_lift\txi^11=sR(z),_iota(xi)=xi\tmu11_subset_Q23_and_11_odd";
print "graded_swan_coefficient\tfunctional_equation\tB0(tau(z))=B0(z)\tin(b_H)=8s^2xiB0_fixed";
print "involution_quotient\tinvariant_coordinate\tu=z^2/(z-1)\tF23(z)^tau=F23(u)";
print "residual_norm_quotient\tquartic_factorization\tY=15*(u^4-u^3+8u^2+4u+1)\texact_over_F23(u)";
print "residual_quartic\tcritical_passport\tinfinity:(4),18:(3,1),1:(2,1,1)\tgeometric_monodromy_S4";
print "residual_quartic\tunique_triple_critical_point\tu=4\tH(u)-18=15*(u-4)^3*(u-12)";
print "residual_quartic\tshabat_normal_form\tX=4*(u-4),W=4*(H-18),W=X^3*(4-3X)\tcritical_coordinate_value_is_not_intrinsic";
print "residual_quartic\tintrinsic_cross_ratio_phase\t(u_simple-u_triple)/(u_double-u_triple)=9\torientation_reversal_9_maps_to_4";
print "graded_swan_quotient\tquartic_formula\tB0=-(u-4)^4/H(u)\texact_over_F23(u)";
print "wild_character_packets\tbranch_exchange\tsquares<->nonsquares\t23A<->23B";
print "# PASS_P23_SEMILINEAR_COVARIANCE_MAGMA_CERTIFICATE";
'''


STABLE_GROUP = r'''// Exact group certificate for the characteristic-23 stable fiber.

procedure Must(flag, message)
    if not flag then
        print "CERTIFICATE_FAILURE: " cat message;
        quit;
    end if;
end procedure;

S := Sym(23);
gA := S!(1,2)(3,4)(7,8)(9,10)(13,14)(15,16)(19,20)(21,22);
gB := S!(1,16,11,3)(2,9,21,12)(4,5,8,23)(6,22,14,18)(13,20)(15,17);
G := sub<S | gA, gB>;
P := SylowSubgroup(G, 23);
N := Normalizer(G, P);
C := Centralizer(G, P);
sigma := Rep({ element : element in P | Order(element) eq 23 });

function ConjugationExponents(group, generator)
    values := {};
    for element in group do
        conjugate := generator^element;
        for exponent in [1..22] do
            if generator^exponent eq conjugate then
                Include(~values, exponent);
                break;
            end if;
        end for;
    end for;
    return values;
end function;

exponents := ConjugationExponents(N, sigma);
squares := { (index^2) mod 23 : index in [1..22] };
NS := Normalizer(S, P);
CS := Centralizer(S, P);
s23_exponents := ConjugationExponents(NS, sigma);
Must(#G eq 10200960 and #P eq 23 and #N eq 253 and #C eq 23,
     "wrong M23 local subgroup orders");
Must(exponents eq squares and #exponents eq 11,
     "M23 conjugation exponents are not the nonzero squares mod 23");
Must(#NS eq 506 and #CS eq 23 and s23_exponents eq {1..22},
     "wrong S23 local subgroup data");

exponent_sequence := Sort(Setseq(exponents));
print "group\tinvariant\tvalue\tstatus";
print "M23\torder\t10200960\texact";
print "M23\tC23_normalizer_order\t253\t23:11";
print "M23\tC23_centralizer_order\t23\tC23";
print "M23\tnontrivial_C23_orbits\t11,11\ttwo_oriented_packets";
printf "M23\tnormalizer_exponents\t%o\tnonzero_squares_mod_23\n",
       Join([ IntegerToString(value) : value in exponent_sequence ], ",");
print "S23\tC23_normalizer_order\t506\t23:22";
print "S23\tnontrivial_C23_orbits\t22\tpackets_fused";
print "# PASS_CHARACTERISTIC_23_STABLE_GROUP_MAGMA_CERTIFICATE";
'''


def outputs() -> dict[Path, str]:
    hj = hjlppz_preamble()
    elkies = elkies_preamble()
    return {
        OUT / "certify_p23_vertical_different.m": HEADER + hj + elkies + VERTICAL_BODY,
        OUT / "certify_p23_tame_resolvents.m": HEADER + hj + elkies + TAME_BODY,
        OUT / "certify_p23_semilinear_covariance.m": SEMILINEAR,
        OUT / "certify_p23_stable_group.m": STABLE_GROUP,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    arguments = parser.parse_args()
    failed = False
    for path, expected in outputs().items():
        expected = expected.rstrip() + "\n"
        if arguments.check:
            actual = path.read_text() if path.exists() else ""
            if actual != expected:
                failed = True
                print(f"OUT OF DATE: {path.relative_to(ROOT)}")
                print("".join(difflib.unified_diff(
                    actual.splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile="checked-in",
                    tofile="generated",
                    n=2,
                )))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected)
            print(path.relative_to(ROOT))
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
