// Generated by scripts/emit_magma_suite.py.  Do not edit by hand.
// Apache-2.0.  See ../../LICENSE and ../../NOTICE.
// Self-contained for the 50,000-byte, 60-second Sydney Magma Calculator.

procedure Must(flag, message)
    if not flag then
        print "CERTIFICATE_FAILURE: " cat message;
        quit;
    end if;
end procedure;

function V23Integer(n)
    if n eq 0 then
        return 10^9;
    end if;
    n := Abs(Integers()!n);
    value := 0;
    while n mod 23 eq 0 do
        n div:= 23;
        value +:= 1;
    end while;
    return value;
end function;

function V23Rational(q)
    if q eq 0 then
        return 10^9;
    end if;
    return V23Integer(Numerator(q)) - V23Integer(Denominator(q));
end function;

Q := Rationals();
QT<T> := PolynomialRing(Q);
b := [ QT!0 : index in [1..23] ];
b[2] +:= (-31740)*T^0;
b[3] +:= (139840)*T^0;
b[4] +:= (399583002)*T^0;
b[5] +:= (-145711496856)*T^0;
b[5] +:= (-6335282472)*T^2;
b[6] +:= (-56775283856672)*T^0;
b[6] +:= (-126169394688)*T^1;
b[6] +:= (-2477993869792)*T^2;
b[7] +:= (2353269564340584)*T^0;
b[7] +:= (90885386323584)*T^1;
b[7] +:= (69899701328472)*T^2;
b[8] +:= (149300207182735461)*T^0;
b[8] +:= (8192572384010400)*T^1;
b[8] +:= (7690149863466435)*T^2;
b[9] +:= (-18518819166678845600)*T^0;
b[9] +:= (-1840547483855390880)*T^1;
b[9] +:= (-181770736706490688)*T^2;
b[10] +:= (5230550645390156540328)*T^0;
b[10] +:= (-2949856937205019309008)*T^1;
b[10] +:= (-72054287980811706816)*T^2;
b[10] +:= (-128254649443696491696)*T^3;
b[10] +:= (-13020414497067723624)*T^4;
b[11] +:= (1780732430570005145756424)*T^0;
b[11] +:= (328246325556276597513504)*T^1;
b[11] +:= (54631308621463631478480)*T^2;
b[11] +:= (14271579372012025978848)*T^3;
b[11] +:= (-990949588424086241496)*T^4;
b[12] +:= (-76226757591131329290382566)*T^0;
b[12] +:= (18690086460439084348196768)*T^1;
b[12] +:= (-1792012713435085812396596)*T^2;
b[12] +:= (813235953706896182384992)*T^3;
b[12] +:= (66027458205719035669658)*T^4;
b[13] +:= (-3875581272261943207482299424)*T^0;
b[13] +:= (-1272104594358533124234481632)*T^1;
b[13] +:= (-28978388560551190877922912)*T^2;
b[13] +:= (-57786540191941872595499808)*T^3;
b[13] +:= (5516437740989208066312576)*T^4;
b[14] +:= (6910353957998684922380692854804)*T^0;
b[14] +:= (-1182608554123854417720035133648)*T^1;
b[14] +:= (412254292452214768806833373492)*T^2;
b[14] +:= (-112352637513414760653499408224)*T^3;
b[14] +:= (-268507225604280859145871012)*T^4;
b[14] +:= (-2649342360462542679225805776)*T^5;
b[14] +:= (-223024171179988438782332580)*T^6;
b[15] +:= (88514359848681198441339995596152)*T^0;
b[15] +:= (66671928552879672571499601603168)*T^1;
b[15] +:= (3059716724605899534195931323384)*T^2;
b[15] +:= (6093776240613995660154706708800)*T^3;
b[15] +:= (-371653155370716716161147483224)*T^4;
b[15] +:= (138912901665864324408428455008)*T^5;
b[15] +:= (-14667842854307851869352629528)*T^6;
b[16] +:= (-14822900658422153993723820208138521)*T^0;
b[16] +:= (1452165788444071252451127163115616)*T^1;
b[16] +:= (-1196200268441385838255312662361293)*T^2;
b[16] +:= (152476099696291565105489515500864)*T^3;
b[16] +:= (-18425610081301084564482099762651)*T^4;
b[16] +:= (3884280726976625226796090157664)*T^5;
b[16] +:= (241847438376053797282595566017)*T^6;
b[17] +:= (-37724221633317849821253387809988360)*T^0;
b[17] +:= (-93620123757549254929872648043284768)*T^1;
b[17] +:= (-11591484764381099858905769639925000)*T^2;
b[17] +:= (-9513428443869186509439824732200896)*T^3;
b[17] +:= (-183430444487395254543895866578136)*T^4;
b[17] +:= (-236651664369455642319930663132960)*T^5;
b[17] +:= (10836296771070547980591633146088)*T^6;
b[18] +:= (16313110767605628611806394020375426680)*T^0;
b[18] +:= (-1703402197188364617307749292365354672)*T^1;
b[18] +:= (2032301462095753658490946401570018888)*T^2;
b[18] +:= (-129191517104013848445270031021659552)*T^3;
b[18] +:= (66730153393082520871679625793751304)*T^4;
b[18] +:= (-2396348444989357771279301994069936)*T^5;
b[18] +:= (400540174533969410487588483397176)*T^6;
b[19] +:= (1042289893847058025879040880566456994672)*T^0;
b[19] +:= (1104530349771039454874170579417691649312)*T^1;
b[19] +:= (333274964387577672914755115261072851872)*T^2;
b[19] +:= (177834072940944271142086313365199175072)*T^3;
b[19] +:= (33713454389094699008417352295983275904)*T^4;
b[19] +:= (9164364930275864576578604398808309088)*T^5;
b[19] +:= (1384908138976241457553823117871919200)*T^6;
b[19] +:= (153061208206234369985720974684614624)*T^7;
b[19] +:= (20149993182414522853209191222911248)*T^8;
b[20] +:= (-146676777647046733368141103212933368381760)*T^0;
b[20] +:= (47248616899864784417985500825997188919648)*T^1;
b[20] +:= (-31059705710059767703037569543512462548640)*T^2;
b[20] +:= (6607721732088306642342716918797881821280)*T^3;
b[20] +:= (-1955502285158879811215641219926699021600)*T^4;
b[20] +:= (309985639130842180423097734341104122656)*T^5;
b[20] +:= (-43709389872759776381483477984786375904)*T^6;
b[20] +:= (4870010697957528157139945192741841696)*T^7;
b[20] +:= (-232445893979612361670227977985803808)*T^8;
b[21] +:= (-583036461536128584530382312820824598910208)*T^0;
b[21] +:= (-368473907347056952685077902822090105858432)*T^1;
b[21] +:= (-250848528005315471356262109412820000004480)*T^2;
b[21] +:= (-37680222996348867437415628143362965239168)*T^3;
b[21] +:= (-35962460177914556876631229408057982882688)*T^4;
b[21] +:= (-781880924013941195027394050639518996608)*T^5;
b[21] +:= (-1778174960398790720078613827770306312320)*T^6;
b[21] +:= (6949635305793713011094772062706710400)*T^7;
b[21] +:= (-27863654688345929867754261488819291520)*T^8;
b[22] +:= (11431517330337822220551952458477060842204160)*T^0;
b[22] +:= (-25809360722373312049323407405759781746499072)*T^1;
b[22] +:= (1790686750434671697130166091520203419410944)*T^2;
b[22] +:= (-2397163462662484578984858522494100321357312)*T^3;
b[22] +:= (173980809918790171381794345879079128660480)*T^4;
b[22] +:= (-86205619580095394601076747481250376567296)*T^5;
b[22] +:= (9150869839919949982069223354218905122304)*T^6;
b[22] +:= (-1337829690063830893124127624391955581440)*T^7;
b[22] +:= (175303343058828611905721103152276390400)*T^8;
b[23] +:= (-636600898150484328800300139882417037526114304)*T^0;
b[23] +:= (-1454239686461893222545991110390844910530811904)*T^1;
b[23] +:= (-352689535457875303125555026318811624811247616)*T^2;
b[23] +:= (103352070659831277568590719722025029106073600)*T^3;
b[23] +:= (15315119499810615305853634694027898506182656)*T^4;
b[23] +:= (32961183987151578191197448811534368526176256)*T^5;
b[23] +:= (4181405479539036486753938644987111713705984)*T^6;
b[23] +:= (1801978935221572204239176449303804249128960)*T^7;
b[23] +:= (172171892687016253525660128823927540899840)*T^8;
b[23] +:= (29729556023869614361220075333404061337600)*T^9;
b[23] +:= (2001532669196828324472937945546023168000)*T^10;

KQT := FieldOfFractions(QT);
RV<V> := PolynomialRing(KQT);
F := V^23 + &+[ (KQT!b[index])/(T^2+23)^(Floor(5*index/23))*V^(23-index)
                  : index in [2..23] ];
Must(Degree(F) eq 23, "the HJLPPZ polynomial lost degree 23");

Qpi<Xpi> := PolynomialRing(Q);
Kpi<pi> := NumberField(Xpi^4-23*Xpi^3+207*Xpi^2-874*Xpi+1472);
g := pi-6;
Must(g^4+g^3+9*g^2-10*g+8 eq 0, "the Elkies quartic changed");
Kx<x> := PolynomialRing(Kpi);
P2_elkies := (8*g^3 + 16*g^2 - 20*g + 20)*x^2 - (7*g^3 + 17*g^2 - 7*g + 76)*x - 13*g^3 + 25*g^2 - 107*g + 596;
P3_elkies := 8*(31*g^3 + 405*g^2 - 459*g + 333)*x^3 + (941*g^3 + 1303*g^2 - 1853*g + 1772)*x + 85*g^3 - 385*g^2 + 395*g - 220;
P4_elkies := 32*(4*g^3 - 69*g^2 + 74*g - 49)*x^4 + 32*(21*g^3 + 53*g^2 - 68*g + 58)*x^3 - 8*(97*g^3 + 95*g^2 - 145*g + 148)*x^2 + 8*(41*g^3 - 89*g^2 - g + 140)*x - 123*g^3 + 391*g^2 - 93*g + 3228;
tau_elkies := (2^38 * 3^17 / 23^3) * (47323*g^3 - 1084897*g^2 + 7751*g - 711002);
P_elkies := P2_elkies^2*P3_elkies*P4_elkies^4;

function VPi(a)
    if a eq 0 then
        return 10^9;
    end if;
    coefficients := Eltseq(Kpi!a);
    return Min([ 4*V23Rational(coefficients[index])+(index-1)
                 : index in [1..#coefficients] ]);
end function;

F23 := GF(23);
function ResiduePi(a)
    coefficients := Eltseq(Kpi!a);
    Must(Min([ 4*V23Rational(coefficients[index])+(index-1)
               : index in [1..#coefficients] ]) ge 0,
         "attempted to reduce a nonintegral pi-adic element");
    return F23!coefficients[1];
end function;

// Exact tame degree-11 Kummer-resolvent certificate at characteristic 23.

squares := { (index^2) mod 23 : index in [1..22] };
Must(squares eq {1,2,3,4,6,8,9,12,13,16,18},
     "the quadratic-residue packet changed");
Must((&*[ index : index in squares ]) mod 23 eq 1,
     "the quadratic-residue packet has the wrong product");

q := T^2+23;
discriminant_hj := Discriminant(F);
numerator_factors := Factorization(Numerator(discriminant_hj));
degree_84_factors := [ factor[1] : factor in numerator_factors |
                       Degree(factor[1]) eq 84 and factor[2] eq 2 ];
Must(#degree_84_factors eq 1, "missing HJ degree-84 square factor");
G84_monic := degree_84_factors[1];
denominator_lcm := LCM([ Denominator(Coefficient(G84_monic, degree))
                         : degree in [0..84] ]);
G84_integer := denominator_lcm*G84_monic;
coefficient_gcd := GCD([ Abs(Numerator(Coefficient(G84_integer, degree)))
                         : degree in [0..84] ]);
G84 := G84_integer/coefficient_gcd;
if LeadingCoefficient(G84) lt 0 then
    G84 := -G84;
end if;
a0 := 2^105*3^36*23^37;
AH := a0*T^4*G84/q^44;
Must(AH^2 eq discriminant_hj,
     "wrong HJ oriented discriminant square root");
hH := 2^9*3^3*23^5/q^4;
lambdaH := 2^6*3^3*T^4*G84/23^18;
Must(AH eq hH^11*lambdaH,
     "wrong HJ eleventh-power normalization");

F23W<w> := PolynomialRing(F23);
weighted_minimum := 10^9;
lambda_residue := F23W!0;
for degree in [0..84] do
    coefficient := Coefficient(G84, degree);
    if coefficient ne 0 then
        weight := 2*V23Rational(coefficient)+degree;
        weighted_minimum := Min(weighted_minimum, weight);
        if weight eq 33 then
            Must(degree mod 2 eq 1, "HJ first-grade parity failure");
            first_grade := 2^6*3^3*coefficient/((-23)^((33-degree) div 2));
            lambda_residue +:= (F23!first_grade)*w^(degree+4);
        end if;
    end if;
end for;
Must(weighted_minimum eq 33,
     "wrong HJ weighted valuation of the degree-84 factor");
// The minus sign is the w-coordinate unit; replacing 2-w by w-2 in the
// published z-coordinate cancels it because the denominator exponent is 37.
Must(lambda_residue eq -w^15*(w^2+6)^11,
     "wrong HJ initial tame Kummer parameter");
YH := -b[23]/q^5;
Must(KQT!YH eq -Coefficient(F, 0), "wrong HJ root norm");

Kpit<t> := RationalFunctionField(Kpi);
KpitY<yt> := PolynomialRing(Kpit);
p23 := LeadingCoefficient(P_elkies);
q23 := p23*pi^-23;
raw_elkies := Evaluate(P_elkies, pi^-1*yt)/tau_elkies-t;
leading_elkies := Coefficient(raw_elkies, 23);
Must(leading_elkies eq q23/tau_elkies,
     "wrong Elkies scaled leading coefficient");
monic_elkies := raw_elkies/leading_elkies;
discriminant_elkies := Discriminant(monic_elkies);
sE := (2*g^3+4*g^2+16*g-7)/3;
Must(sE^2 eq -23, "wrong Elkies square root of -23");
Must(VPi(sE) eq 2, "wrong valuation of the Elkies quadratic uniformizer");
hE := 23*tau_elkies*pi^23/p23;
lambdaE := sE*t^7*(t-1)^4;
AE := hE^11*lambdaE;
Must(discriminant_elkies eq AE^2,
     "wrong Elkies oriented discriminant square root");
Must(VPi(hE) eq 4, "wrong Elkies eleventh-power scaling valuation");
Must(ResiduePi(sE/pi^2) eq F23!-3,
     "wrong Elkies initial tame Kummer unit");
Must(ResiduePi(hE/pi^4) eq F23!11,
     "wrong Elkies b-scaling unit");
P0 := Evaluate(P_elkies, 0);
YE := (tau_elkies*t-P0)/q23;
Must(YE eq -Coefficient(monic_elkies, 0), "wrong Elkies root norm");
ye_denominator := Denominator(YE);
Must(Degree(ye_denominator) eq 0, "Elkies root norm denominator changed");
ye_scale := Coefficient(ye_denominator, 0);
Must(ResiduePi(Coefficient(Numerator(YE), 1)/ye_scale) eq F23!9 and
     ResiduePi(Coefficient(Numerator(YE), 0)/ye_scale) eq F23!0,
     "wrong Elkies residual root norm");

print "cover\tprime\tinvariant\tvalue\tstatus";
print "both\t23\toriented_cycle_norm_identity\tA^2=Disc(f)\tA=product_(q_square)C_q";
print "both\t23\tdegree_11_oriented_resolvent\tproduct_(q_square)(U-C_q)\tconstant_term=-A";
print "hjlppz\t23\tdiscriminant_square_root\t2^105*3^36*23^37*T^4*G84(T)/(T^2+23)^44\texact_G84_degree_84";
print "hjlppz\t23\ttame_kummer_parameter\tLambda_H=2^6*3^3*T^4*G84(T)/23^18\tv_s(Lambda_H)=1";
print "hjlppz\t23\ttame_degree_11_resolvent\tX^11-Lambda_H\tEisenstein_over_Q23(s)(z)";
print "hjlppz\t23\ttame_parameter_initial_unit\tz^15*(z^2+13*z+10)^11/(z-2)^37\tLambda_H/s_mod_s";
print "hjlppz\t23\troot_norm_Y_H\t-b_23(T)/(T^2+23)^5\treduces_to_-E(z)/(z-1)^5";
print "hjlppz\t23\tgraded_b_H\tin(b_H)=in(h_H*theta_H/Y_H)\ttheta_H^11=Lambda_H";
print "hjlppz\t23\tgraded_b_H_explicit\t8*s^2*xi_H*(z-2)^8*(z-1)/E(z)\txi_H^11=s*z^15*(z^2+13*z+10)^11/(z-2)^37";
print "elkies\t23\tsqrt_minus_23\t(2*g^3+4*g^2+16*g-7)/3\ts_E^2=-23";
print "elkies\t23\tdiscriminant_square_root\ts_E*(23*tau*pi^23/p_23)^11*t^7*(t-1)^4\texact_over_F(t)";
print "elkies\t23\ttame_kummer_parameter\tLambda_E=s_E*t^7*(t-1)^4\tv_pi(Lambda_E)=2";
print "elkies\t23\ttame_degree_11_resolvent\tX^11-Lambda_E\ttotally_tame_degree_11";
print "elkies\t23\ttame_parameter_initial_unit\t-3*t^7*(t-1)^4\tLambda_E/pi^2_mod_pi";
print "elkies\t23\troot_norm_Y_E\t(tau*t-P(0))/(p_23*pi^-23)\treduces_to_t/18";
print "elkies\t23\tgraded_b_E\tin(b_E)=in(h_E*theta_E/Y_E)\ttheta_E^11=Lambda_E";
print "elkies\t23\tgraded_b_E_explicit\t14*pi^4*xi_E/t\txi_E^11=-3*pi^2*t^7*(t-1)^4";
print "# PASS_CHARACTERISTIC_23_TAME_RESOLVENT_MAGMA_CERTIFICATE";
