// Generated by scripts/emit_magma_suite.py.  Do not edit by hand.
// Apache-2.0.  See ../../LICENSE and ../../NOTICE.
// Self-contained for the 50,000-byte, 60-second Sydney Magma Calculator.

procedure Must(flag, message)
    if not flag then
        print "CERTIFICATE_FAILURE: " cat message;
        quit;
    end if;
end procedure;

function V23Integer(n)
    if n eq 0 then
        return 10^9;
    end if;
    n := Abs(Integers()!n);
    value := 0;
    while n mod 23 eq 0 do
        n div:= 23;
        value +:= 1;
    end while;
    return value;
end function;

function V23Rational(q)
    if q eq 0 then
        return 10^9;
    end if;
    return V23Integer(Numerator(q)) - V23Integer(Denominator(q));
end function;

// Exact semilinear branch-exchange covariance at the HJLPPZ p=23 stable Gauss valuation.

F23 := GF(23);
F23z<z> := RationalFunctionField(F23);
F23u<u> := RationalFunctionField(F23);

function SubstituteRational(function_value, argument)
    return Evaluate(Numerator(function_value), argument)/
           Evaluate(Denominator(function_value), argument);
end function;

tau := z/(z-1);
E := 8*z^9+7*z^8+11*z^7+16*z^6+3*z^5+19*z^4+21*z^3+21*z^2+17*z+15;
Y := -E/(z-1)^5;
R := z^15*(z^2+13*z+10)^11/(z-2)^37;
B0 := (z-2)^8*(z-1)/E;
swanform := Derivative(Y)/Y;
quotient_coordinate := z^2/(z-1);
H := 15*(u^4-u^3+8*u^2+4*u+1);
shabat_source := 4*(u-4);
shabat_target := 4*(H-18);
wild_phase := F23!(12-4)/F23!(10-4);
wild_phase_reversal := wild_phase/(wild_phase-1);

Must(SubstituteRational(tau, tau) eq z, "the target branch exchange is not involutive");
Must(SubstituteRational(Y, tau) eq Y, "the residual norm is not branch-exchange invariant");
Must(SubstituteRational(swanform, tau)*Derivative(tau) eq swanform,
     "the logarithmic Swan differential is not invariant");
Must(SubstituteRational(R, tau) eq -R,
     "the Kummer initial unit does not acquire the required sign");
Must(SubstituteRational(B0, tau) eq B0,
     "the graded Swan rational coefficient is not invariant");
Must((z-1)^10*SubstituteRational(E, tau) eq E,
     "the polynomial functional equation for E failed");
Must(SubstituteRational(quotient_coordinate, tau) eq quotient_coordinate,
     "u does not generate a tau-invariant quotient coordinate");
Must(SubstituteRational(H, quotient_coordinate) eq Y,
     "the residual norm does not factor through H(u)");
Must(Derivative(H) eq 14*(u-4)^2*(u-10), "the quartic critical divisor changed");
Must(H-18 eq 15*(u-4)^3*(u-12), "the quartic triple fibre changed");
Must(H-1 eq 15*(u-10)^2*(u^2+19*u+12), "the quartic double fibre changed");
Must(SubstituteRational(-(u-4)^4/H, quotient_coordinate) eq B0,
     "the Swan coefficient does not descend to the quartic quotient");
Must(shabat_target eq shabat_source^3*(4-3*shabat_source),
     "the residual quartic Shabat normal form changed");
Must(wild_phase eq 9 and wild_phase_reversal eq 4,
     "the residual quartic intrinsic phase changed");
Must((23-1) mod 11 eq 0, "mu_11 is not contained in the unramified units");
squares := {1,2,3,4,6,8,9,12,13,16,18};
nonsquares := {5,7,10,11,14,15,17,19,20,21,22};
Must({ (-value) mod 23 : value in squares } eq nonsquares,
     "the square and nonsquare packets are not exchanged by reversal");

print "object\tinvariant\tvalue\tstatus";
print "target\tbranch_exchange\t(s,z)->(-s,z/(z-1))\torder_2";
print "residual_norm\tfunctional_equation\tY(tau(z))=Y(z)\texact_over_F23(z)";
print "residual_polynomial\tsemilinear_symmetry\tV^23=Y(z)\tV_fixed_on_residue";
print "swan_differential\tfunctional_equation\ttau^*dlog(Y)=dlog(Y)\texact_over_F23(z)";
print "tame_kummer_unit\tfunctional_equation\tR(tau(z))=-R(z)\tsR(z)_fixed_under_s_to_-s";
print "tame_kummer_root\tinvolutive_lift\txi^11=sR(z),_iota(xi)=xi\tmu11_subset_Q23_and_11_odd";
print "graded_swan_coefficient\tfunctional_equation\tB0(tau(z))=B0(z)\tin(b_H)=8s^2xiB0_fixed";
print "involution_quotient\tinvariant_coordinate\tu=z^2/(z-1)\tF23(z)^tau=F23(u)";
print "residual_norm_quotient\tquartic_factorization\tY=15*(u^4-u^3+8u^2+4u+1)\texact_over_F23(u)";
print "residual_quartic\tcritical_passport\tinfinity:(4),18:(3,1),1:(2,1,1)\tgeometric_monodromy_S4";
print "residual_quartic\tunique_triple_critical_point\tu=4\tH(u)-18=15*(u-4)^3*(u-12)";
print "residual_quartic\tshabat_normal_form\tX=4*(u-4),W=4*(H-18),W=X^3*(4-3X)\tcritical_coordinate_value_is_not_intrinsic";
print "residual_quartic\tintrinsic_cross_ratio_phase\t(u_simple-u_triple)/(u_double-u_triple)=9\torientation_reversal_9_maps_to_4";
print "graded_swan_quotient\tquartic_formula\tB0=-(u-4)^4/H(u)\texact_over_F23(u)";
print "wild_character_packets\tbranch_exchange\tsquares<->nonsquares\t23A<->23B";
print "# PASS_P23_SEMILINEAR_COVARIANCE_MAGMA_CERTIFICATE";
