// Generated by scripts/emit_magma_suite.py.  Do not edit by hand.
// Apache-2.0.  See ../../LICENSE and ../../NOTICE.
// Self-contained for the 50,000-byte, 60-second Sydney Magma Calculator.

procedure Must(flag, message)
    if not flag then
        print "CERTIFICATE_FAILURE: " cat message;
        quit;
    end if;
end procedure;

function V23Integer(n)
    if n eq 0 then
        return 10^9;
    end if;
    n := Abs(Integers()!n);
    value := 0;
    while n mod 23 eq 0 do
        n div:= 23;
        value +:= 1;
    end while;
    return value;
end function;

function V23Rational(q)
    if q eq 0 then
        return 10^9;
    end if;
    return V23Integer(Numerator(q)) - V23Integer(Denominator(q));
end function;

Q := Rationals();
QT<T> := PolynomialRing(Q);
b := [ QT!0 : index in [1..23] ];
b[2] +:= (-31740)*T^0;
b[3] +:= (139840)*T^0;
b[4] +:= (399583002)*T^0;
b[5] +:= (-145711496856)*T^0;
b[5] +:= (-6335282472)*T^2;
b[6] +:= (-56775283856672)*T^0;
b[6] +:= (-126169394688)*T^1;
b[6] +:= (-2477993869792)*T^2;
b[7] +:= (2353269564340584)*T^0;
b[7] +:= (90885386323584)*T^1;
b[7] +:= (69899701328472)*T^2;
b[8] +:= (149300207182735461)*T^0;
b[8] +:= (8192572384010400)*T^1;
b[8] +:= (7690149863466435)*T^2;
b[9] +:= (-18518819166678845600)*T^0;
b[9] +:= (-1840547483855390880)*T^1;
b[9] +:= (-181770736706490688)*T^2;
b[10] +:= (5230550645390156540328)*T^0;
b[10] +:= (-2949856937205019309008)*T^1;
b[10] +:= (-72054287980811706816)*T^2;
b[10] +:= (-128254649443696491696)*T^3;
b[10] +:= (-13020414497067723624)*T^4;
b[11] +:= (1780732430570005145756424)*T^0;
b[11] +:= (328246325556276597513504)*T^1;
b[11] +:= (54631308621463631478480)*T^2;
b[11] +:= (14271579372012025978848)*T^3;
b[11] +:= (-990949588424086241496)*T^4;
b[12] +:= (-76226757591131329290382566)*T^0;
b[12] +:= (18690086460439084348196768)*T^1;
b[12] +:= (-1792012713435085812396596)*T^2;
b[12] +:= (813235953706896182384992)*T^3;
b[12] +:= (66027458205719035669658)*T^4;
b[13] +:= (-3875581272261943207482299424)*T^0;
b[13] +:= (-1272104594358533124234481632)*T^1;
b[13] +:= (-28978388560551190877922912)*T^2;
b[13] +:= (-57786540191941872595499808)*T^3;
b[13] +:= (5516437740989208066312576)*T^4;
b[14] +:= (6910353957998684922380692854804)*T^0;
b[14] +:= (-1182608554123854417720035133648)*T^1;
b[14] +:= (412254292452214768806833373492)*T^2;
b[14] +:= (-112352637513414760653499408224)*T^3;
b[14] +:= (-268507225604280859145871012)*T^4;
b[14] +:= (-2649342360462542679225805776)*T^5;
b[14] +:= (-223024171179988438782332580)*T^6;
b[15] +:= (88514359848681198441339995596152)*T^0;
b[15] +:= (66671928552879672571499601603168)*T^1;
b[15] +:= (3059716724605899534195931323384)*T^2;
b[15] +:= (6093776240613995660154706708800)*T^3;
b[15] +:= (-371653155370716716161147483224)*T^4;
b[15] +:= (138912901665864324408428455008)*T^5;
b[15] +:= (-14667842854307851869352629528)*T^6;
b[16] +:= (-14822900658422153993723820208138521)*T^0;
b[16] +:= (1452165788444071252451127163115616)*T^1;
b[16] +:= (-1196200268441385838255312662361293)*T^2;
b[16] +:= (152476099696291565105489515500864)*T^3;
b[16] +:= (-18425610081301084564482099762651)*T^4;
b[16] +:= (3884280726976625226796090157664)*T^5;
b[16] +:= (241847438376053797282595566017)*T^6;
b[17] +:= (-37724221633317849821253387809988360)*T^0;
b[17] +:= (-93620123757549254929872648043284768)*T^1;
b[17] +:= (-11591484764381099858905769639925000)*T^2;
b[17] +:= (-9513428443869186509439824732200896)*T^3;
b[17] +:= (-183430444487395254543895866578136)*T^4;
b[17] +:= (-236651664369455642319930663132960)*T^5;
b[17] +:= (10836296771070547980591633146088)*T^6;
b[18] +:= (16313110767605628611806394020375426680)*T^0;
b[18] +:= (-1703402197188364617307749292365354672)*T^1;
b[18] +:= (2032301462095753658490946401570018888)*T^2;
b[18] +:= (-129191517104013848445270031021659552)*T^3;
b[18] +:= (66730153393082520871679625793751304)*T^4;
b[18] +:= (-2396348444989357771279301994069936)*T^5;
b[18] +:= (400540174533969410487588483397176)*T^6;
b[19] +:= (1042289893847058025879040880566456994672)*T^0;
b[19] +:= (1104530349771039454874170579417691649312)*T^1;
b[19] +:= (333274964387577672914755115261072851872)*T^2;
b[19] +:= (177834072940944271142086313365199175072)*T^3;
b[19] +:= (33713454389094699008417352295983275904)*T^4;
b[19] +:= (9164364930275864576578604398808309088)*T^5;
b[19] +:= (1384908138976241457553823117871919200)*T^6;
b[19] +:= (153061208206234369985720974684614624)*T^7;
b[19] +:= (20149993182414522853209191222911248)*T^8;
b[20] +:= (-146676777647046733368141103212933368381760)*T^0;
b[20] +:= (47248616899864784417985500825997188919648)*T^1;
b[20] +:= (-31059705710059767703037569543512462548640)*T^2;
b[20] +:= (6607721732088306642342716918797881821280)*T^3;
b[20] +:= (-1955502285158879811215641219926699021600)*T^4;
b[20] +:= (309985639130842180423097734341104122656)*T^5;
b[20] +:= (-43709389872759776381483477984786375904)*T^6;
b[20] +:= (4870010697957528157139945192741841696)*T^7;
b[20] +:= (-232445893979612361670227977985803808)*T^8;
b[21] +:= (-583036461536128584530382312820824598910208)*T^0;
b[21] +:= (-368473907347056952685077902822090105858432)*T^1;
b[21] +:= (-250848528005315471356262109412820000004480)*T^2;
b[21] +:= (-37680222996348867437415628143362965239168)*T^3;
b[21] +:= (-35962460177914556876631229408057982882688)*T^4;
b[21] +:= (-781880924013941195027394050639518996608)*T^5;
b[21] +:= (-1778174960398790720078613827770306312320)*T^6;
b[21] +:= (6949635305793713011094772062706710400)*T^7;
b[21] +:= (-27863654688345929867754261488819291520)*T^8;
b[22] +:= (11431517330337822220551952458477060842204160)*T^0;
b[22] +:= (-25809360722373312049323407405759781746499072)*T^1;
b[22] +:= (1790686750434671697130166091520203419410944)*T^2;
b[22] +:= (-2397163462662484578984858522494100321357312)*T^3;
b[22] +:= (173980809918790171381794345879079128660480)*T^4;
b[22] +:= (-86205619580095394601076747481250376567296)*T^5;
b[22] +:= (9150869839919949982069223354218905122304)*T^6;
b[22] +:= (-1337829690063830893124127624391955581440)*T^7;
b[22] +:= (175303343058828611905721103152276390400)*T^8;
b[23] +:= (-636600898150484328800300139882417037526114304)*T^0;
b[23] +:= (-1454239686461893222545991110390844910530811904)*T^1;
b[23] +:= (-352689535457875303125555026318811624811247616)*T^2;
b[23] +:= (103352070659831277568590719722025029106073600)*T^3;
b[23] +:= (15315119499810615305853634694027898506182656)*T^4;
b[23] +:= (32961183987151578191197448811534368526176256)*T^5;
b[23] +:= (4181405479539036486753938644987111713705984)*T^6;
b[23] +:= (1801978935221572204239176449303804249128960)*T^7;
b[23] +:= (172171892687016253525660128823927540899840)*T^8;
b[23] +:= (29729556023869614361220075333404061337600)*T^9;
b[23] +:= (2001532669196828324472937945546023168000)*T^10;

KQT := FieldOfFractions(QT);
RV<V> := PolynomialRing(KQT);
F := V^23 + &+[ (KQT!b[index])/(T^2+23)^(Floor(5*index/23))*V^(23-index)
                  : index in [2..23] ];
Must(Degree(F) eq 23, "the HJLPPZ polynomial lost degree 23");

Qpi<Xpi> := PolynomialRing(Q);
Kpi<pi> := NumberField(Xpi^4-23*Xpi^3+207*Xpi^2-874*Xpi+1472);
g := pi-6;
Must(g^4+g^3+9*g^2-10*g+8 eq 0, "the Elkies quartic changed");
Kx<x> := PolynomialRing(Kpi);
P2_elkies := (8*g^3 + 16*g^2 - 20*g + 20)*x^2 - (7*g^3 + 17*g^2 - 7*g + 76)*x - 13*g^3 + 25*g^2 - 107*g + 596;
P3_elkies := 8*(31*g^3 + 405*g^2 - 459*g + 333)*x^3 + (941*g^3 + 1303*g^2 - 1853*g + 1772)*x + 85*g^3 - 385*g^2 + 395*g - 220;
P4_elkies := 32*(4*g^3 - 69*g^2 + 74*g - 49)*x^4 + 32*(21*g^3 + 53*g^2 - 68*g + 58)*x^3 - 8*(97*g^3 + 95*g^2 - 145*g + 148)*x^2 + 8*(41*g^3 - 89*g^2 - g + 140)*x - 123*g^3 + 391*g^2 - 93*g + 3228;
tau_elkies := (2^38 * 3^17 / 23^3) * (47323*g^3 - 1084897*g^2 + 7751*g - 711002);
P_elkies := P2_elkies^2*P3_elkies*P4_elkies^4;

function VPi(a)
    if a eq 0 then
        return 10^9;
    end if;
    coefficients := Eltseq(Kpi!a);
    return Min([ 4*V23Rational(coefficients[index])+(index-1)
                 : index in [1..#coefficients] ]);
end function;

F23 := GF(23);
function ResiduePi(a)
    coefficients := Eltseq(Kpi!a);
    Must(Min([ 4*V23Rational(coefficients[index])+(index-1)
               : index in [1..#coefficients] ]) ge 0,
         "attempted to reduce a nonintegral pi-adic element");
    return F23!coefficients[1];
end function;

// Exact first vertical-different certificate at characteristic 23.

Qs<Ss> := PolynomialRing(Q);
Ks<ss> := NumberField(Ss^2+23);
Ksz<z> := RationalFunctionField(Ks);
F23z<z23> := RationalFunctionField(F23);
F23zV<V23> := PolynomialRing(F23z);

function VS(a)
    if a eq 0 then
        return 10^9;
    end if;
    coefficients := Eltseq(Ks!a);
    return Min(2*V23Rational(coefficients[1]),
               2*V23Rational(coefficients[2])+1);
end function;

function ResidueS(a)
    coefficients := Eltseq(Ks!a);
    Must(VS(a) ge 0, "attempted to reduce a nonintegral s-adic element");
    return F23!coefficients[1];
end function;

normalized_hj := V23^22;
hj_valuations := [];
for index in [2..22] do
    denominator_order := Floor(5*index/23);
    raw := Evaluate(b[index], ss*z/(2-z))*(2-z)^(2*denominator_order);
    raw_numerator := Numerator(raw);
    raw_denominator := Denominator(raw);
    Must(Degree(raw_denominator) eq 0,
         "HJ substituted numerator did not become a polynomial");
    polynomial := raw_numerator/Coefficient(raw_denominator, 0);
    valuation := Min([ VS(Coefficient(polynomial, degree))
                       : degree in [0..Degree(polynomial)] ])
                 - 2*denominator_order;
    Append(~hj_valuations, valuation);
    Must(valuation ge 2, "HJ derivative coefficient lies below v(23)");
    if valuation eq 2 then
        scale := 23*(-92)^denominator_order;
        reduced := F23z!0;
        for degree in [0..Degree(polynomial)] do
            reduced +:= ResidueS(Coefficient(polynomial, degree)/scale)*z23^degree;
        end for;
        normalized_hj +:= (F23!(23-index))*reduced/(z23-1)^denominator_order
                          *V23^(22-index);
    end if;
end for;
Must(hj_valuations eq [4] cat [2 : index in [1..20]],
     "wrong HJ stable derivative coefficient valuations");
Must(Degree(normalized_hj) eq 22 and normalized_hj ne 0,
     "HJ normalized vertical derivative vanished");
denominator_lcm := LCM([ Denominator(Coefficient(normalized_hj, degree))
                         : degree in [0..22] ]);
denominator_lcm /:= LeadingCoefficient(denominator_lcm);
Must(denominator_lcm eq (z23-1)^3,
     "wrong HJ normalized derivative denominator");
normalized_hj_monic := normalized_hj/LeadingCoefficient(normalized_hj);
Must(IsIrreducible(normalized_hj_monic),
     "HJ normalized derivative is reducible over F23(z)");

endpoint := 8*z23^9+7*z23^8+11*z23^7+16*z23^6+3*z23^5+
            19*z23^4+21*z23^3+21*z23^2+17*z23+15;
residual_constant := endpoint/(z23-1)^5;
residual_hj := V23^23+residual_constant;
Must(Derivative(residual_constant) ne 0,
     "HJ residual polynomial is not purely inseparable irreducible");
different_norm_hj := Resultant(residual_hj, normalized_hj);
tail_quadratic := z23^2+13*z23+10;
expected_norm_hj := z23^30*(z23-2)^102*tail_quadratic^22/(z23-1)^88;
Must(different_norm_hj eq expected_norm_hj,
     "wrong HJ first vertical-different norm");
F23Z<Z23> := PolynomialRing(F23);
Must(IsIrreducible(Z23^2+13*Z23+10),
     "HJ quadratic vertical-different locus unexpectedly split");
residual_norm_hj := -residual_constant;
Must(Derivative(residual_norm_hj)/residual_norm_hj ne 0,
     "HJ residual norm differential vanished");

Kpy<y> := PolynomialRing(Kpi);
scaled_elkies := Evaluate(P_elkies, pi^-1*y)/tau_elkies;
normalized_elkies := Derivative(scaled_elkies)/pi^4;
elkies_valuations := [ VPi(Coefficient(normalized_elkies, degree))
                       : degree in [0..22] ];
Must(elkies_valuations eq
     [7,7,6,6,5,5,4,4,3,3,2,2,1,1,0,0,0,0,0,0,0,0,0],
     "wrong Elkies normalized derivative valuations");
F23Y<Y23> := PolynomialRing(F23);
reduced_elkies := &+[ ResiduePi(Coefficient(normalized_elkies, degree))*Y23^degree
                       : degree in [0..22] ];
expected_elkies := -Y23^14*(Y23-9)^8;
Must(reduced_elkies eq expected_elkies,
     "wrong Elkies first vertical derivative");
F23t<t23> := RationalFunctionField(F23);
F23tY<Yt> := PolynomialRing(F23t);
reduced_elkies_t := &+[ F23t!Coefficient(reduced_elkies, degree)*Yt^degree
                         : degree in [0..22] ];
residual_elkies := 18*Yt^23-t23;
different_norm_elkies := Resultant(residual_elkies, reduced_elkies_t);
Must(different_norm_elkies eq -t23^14*(t23-1)^8,
     "wrong Elkies first vertical-different norm");
residual_norm_elkies := t23/18;
Must(Derivative(residual_norm_elkies)/residual_norm_elkies eq 1/t23,
     "wrong Elkies residual norm differential");

print "cover\tprime\tinvariant\tvalue\tstatus";
print "hjlppz\t23\tderivative_coefficient_valuations\t4,2x20\tminimum_2";
print "hjlppz\t23\tnormalized_vertical_derivative\t22\tirreducible_over_F23(z)";
print "hjlppz\t23\tdifferent_norm_divisor\t0:30,2:102,Q2:22,1:-88,infinity:-88\tQ2=z^2+13z+10_irreducible";
print "hjlppz\t23\tmonogenic_different_exponent\t2\tnormalized_derivative_nonzero";
print "hjlppz\t23\tdiscriminant_exponent\t46\t23_times_different";
print "hjlppz\t23\twild_upper_break\t23/22\tmaximal_fierce_C23_break";
print "hjlppz\t23\tresidual_norm_differential\tdlog(-E(z)/(z-1)^5)\tCartier_fixed";
print "hjlppz\t23\trefined_swan_normalization\tb_H^(-1)_tensor_residual_norm_differential\tb_H=N(sigma(x)/x-1)_required";
print "elkies\t23\tderivative_coefficient_valuations\t7,7,6,6,5,5,4,4,3,3,2,2,1,1,0x9\tminimum_0_after_pi4";
print "elkies\t23\tnormalized_vertical_derivative\t-y^14*(y-9)^8\ttail_centers_0,9";
print "elkies\t23\tdifferent_norm_divisor\t0:14,1:8,infinity:-22\trecovers_4A,2A_contributions";
print "elkies\t23\tmonogenic_different_exponent\t4\tnormalized_derivative_nonzero";
print "elkies\t23\tdiscriminant_exponent\t92\t23_times_different";
print "elkies\t23\twild_upper_break\t23/22\tmaximal_fierce_C23_break";
print "elkies\t23\tresidual_norm_differential\tdt/t\tCartier_fixed";
print "elkies\t23\trefined_swan_normalization\tb_E^(-1)_tensor_residual_norm_differential\tb_E=N(sigma(x)/x-1)_required";
print "# PASS_CHARACTERISTIC_23_VERTICAL_DIFFERENT_MAGMA_CERTIFICATE";
